//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roasystemsPortal.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposXUsuario
    {
        public long grupoId { get; set; }
        public long usuarioId { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    }
}
