//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roasystemsPortal.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosXGrupo
    {
        public long moduloId { get; set; }
        public long grupoId { get; set; }
        public long empresaId { get; set; }
        public bool pSELECT { get; set; }
        public bool pINSERT { get; set; }
        public bool pUPDATE { get; set; }
        public bool pDELETE { get; set; }
        public bool pUNDELETE { get; set; }
        public bool pKILL { get; set; }
        public bool pREPORT { get; set; }
        public bool pPRINT { get; set; }
        public bool pDOWNLOAD { get; set; }
        public bool pUPLOAD { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
