//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roasystemsPortal.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosXUsuario
    {
        public long moduloId { get; set; }
        public long usuarioId { get; set; }
        public long empresaId { get; set; }
        public Nullable<bool> pSELECT { get; set; }
        public Nullable<bool> pINSERT { get; set; }
        public Nullable<bool> pUPDATE { get; set; }
        public Nullable<bool> pDELETE { get; set; }
        public Nullable<bool> pUNDELETE { get; set; }
        public Nullable<bool> pKILL { get; set; }
        public Nullable<bool> pREPORT { get; set; }
        public Nullable<bool> pPRINT { get; set; }
        public Nullable<bool> pDOWNLOAD { get; set; }
        public Nullable<bool> pUPLOAD { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
