//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roasystemsPortal.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public long id { get; set; }
        public string loginName { get; set; }
        public byte[] contrasenia { get; set; }
        public byte[] firma { get; set; }
        public string apPaterno { get; set; }
        public string apMaterno { get; set; }
        public string nombres { get; set; }
        public string eMail { get; set; }
        public string tweeter { get; set; }
        public string facebook { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string culture { get; set; }
        public bool requiereCambiarPassword { get; set; }
        public bool requiereCambiarFirma { get; set; }
        public bool esAdmin { get; set; }
        public Nullable<int> diasDuracionContrasenia { get; set; }
        public Nullable<int> diasDuracionFirma { get; set; }
        public Nullable<bool> recibirNotificaciones { get; set; }
        public Nullable<bool> aceptaTerminosDeServicio { get; set; }
        public bool confirmed { get; set; }
        public Nullable<System.DateTime> CONFIRMATION_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public bool DELETED { get; set; }
        public Nullable<long> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    }
}
